services:
  postgres:
    image: postgres:16-alpine
    container_name: weather-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_app
    ports:
      - "5433:5432"
    volumes:
      - weather_pgdata:/var/lib/postgresql/data
      - ./back/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: weather-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      - postgres

  back:
    build: ./back
    container_name: weather-back
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/weather_app
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - postgres

  front:
    build: ./front
    container_name: weather-front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back

volumes:
  weather_pgdata:
